#!/bin/bash
set -e

MODE=${1:-generate}
OUTPUT=$2
shift 2

COMPONENTS=()
VARS=()
SAW_SEPARATOR=0
for arg in "$@"; do
    if [ "$SAW_SEPARATOR" -eq 0 ] && [ "$arg" = "--" ]; then
        SAW_SEPARATOR=1
        continue
    fi
    if [ "$SAW_SEPARATOR" -eq 1 ]; then
        VARS+=("$arg")
    else
        COMPONENTS+=("$arg")
    fi
done

COMPONENTS_LIST=$(printf '#   - %s\n' "${COMPONENTS[@]}")

HEADER="# >>> BEGIN AUTOGENERATED SECTION - config-ci-library
# Do not modify this section directly, instead modify the
# components in pre-commit/configs/components/ and run the
# generate script or commit to trigger regeneration
#
# Generated from:
$COMPONENTS_LIST
repos:"

FOOTER="# >>> END AUTOGENERATED SECTION - config-ci-library
# Add any repo-specific hooks below this line"

GENERATED_CONTENT=$(cat "${COMPONENTS[@]}" | sed 's/^/  /')

for kv in "${VARS[@]}"; do
    KEY=${kv%%=*}
    VALUE=${kv#*=}
    ESCAPED=$(printf '%s' "$VALUE" | sed -e 's/[\&|]/\\&/g')
    GENERATED_CONTENT=$(printf '%s' "$GENERATED_CONTENT" | sed "s|\${${KEY}}|${ESCAPED}|g")
done

GENERATED="$HEADER
$GENERATED_CONTENT
$FOOTER"

if [ "$MODE" = "check" ]; then
    if ! diff <(echo "$GENERATED") "$OUTPUT" > /dev/null 2>&1; then
        echo "ERROR: $OUTPUT is out of date, run the generate script locally"
        exit 1
    fi
    echo "OK: $OUTPUT is up to date"
else
    echo "$GENERATED" > "$OUTPUT"
    git add "$OUTPUT"
    echo "Generated $OUTPUT"
    exit 0
fi
