#!/bin/bash
set -e

MODE=${1:-generate}
OUTPUT=$2
shift 2
COMPONENTS=("$@")

COMPONENTS_LIST=$(printf '#   - %s\n' "${COMPONENTS[@]}")

HEADER="# >>> BEGIN AUTOGENERATED SECTION - config-ci-library
# Do not modify this section directly, instead modify the
# components in pre-commit/configs/components/ and run the
# generate script or commit to trigger regeneration
#
# Generated from:
$COMPONENTS_LIST
repos:"

FOOTER="# >>> END AUTOGENERATED SECTION - config-ci-library
# Add any repo-specific hooks below this line"

GENERATED_CONTENT=$(cat "${COMPONENTS[@]}" | sed 's/^/  /')
GENERATED="$HEADER
$GENERATED_CONTENT
$FOOTER"

if [ "$MODE" = "check" ]; then
    if ! diff <(echo "$GENERATED") "$OUTPUT" > /dev/null 2>&1; then
        echo "ERROR: $OUTPUT is out of date, run the generate script locally"
        exit 1
    fi
    echo "OK: $OUTPUT is up to date"
else
    echo "$GENERATED" > "$OUTPUT"
    git add "$OUTPUT"
    echo "Generated $OUTPUT"
    exit 0
fi
