name: Check pre-commit configs are generated
description: Fails if generated pre-commit configs are out of date

runs:
  using: composite
  steps:
    - name: Check python config is up to date
      run: |
        bash ${{ github.action_path }}/../../../pre-commit/configs/generate.sh \
          check \
          pre-commit/configs/python.pre-commit-config.yaml \
          pre-commit/configs/components/common-base.pre-commit-config-component.yaml \
          pre-commit/configs/components/common-format.pre-commit-config-component.yaml \
          pre-commit/configs/components/python.pre-commit-config-component.yaml
      shell: bash
    - name: Check typescript config is up to date
      run: |
        bash ${{ github.action_path }}/../../../pre-commit/configs/generate.sh \
          check \
          pre-commit/configs/typescript.pre-commit-config.yaml \
          pre-commit/configs/components/common-base.pre-commit-config-component.yaml \
          pre-commit/configs/components/common-format.pre-commit-config-component.yaml \
          pre-commit/configs/components/typescript.pre-commit-config-component.yaml \
          -- \
          TS_DIR=.
      shell: bash
    - name: Check python+typescript config is up to date
      run: |
        bash ${{ github.action_path }}/../../../pre-commit/configs/generate.sh \
          check \
          pre-commit/configs/python+typescript.pre-commit-config.yaml \
          pre-commit/configs/components/common-base.pre-commit-config-component.yaml \
          pre-commit/configs/components/common-format.pre-commit-config-component.yaml \
          pre-commit/configs/components/python.pre-commit-config-component.yaml \
          pre-commit/configs/components/typescript.pre-commit-config-component.yaml \
          -- \
          TS_DIR=ui
      shell: bash
    - name: Check golang config is up to date
      run: |
        bash ${{ github.action_path }}/../../../pre-commit/configs/generate.sh \
          check \
          pre-commit/configs/golang.pre-commit-config.yaml \
          pre-commit/configs/components/common-base.pre-commit-config-component.yaml \
          pre-commit/configs/components/common-format.pre-commit-config-component.yaml \
          pre-commit/configs/components/golang.pre-commit-config-component.yaml
      shell: bash
    - name: Check kubernetes config is up to date
      run: |
        bash ${{ github.action_path }}/../../../pre-commit/configs/generate.sh \
          check \
          pre-commit/configs/kubernetes.pre-commit-config.yaml \
          pre-commit/configs/components/common-base.pre-commit-config-component.yaml \
          pre-commit/configs/components/kubernetes.pre-commit-config-component.yaml
      shell: bash
